-- ============================================================
-- Migration 040 — Membership program (check-ins, points, rewards,
-- free pours, beer journal, badges)
-- ============================================================
-- The membership tables have been in schema.sql since v1 as bare
-- shapes carried over from the first staff panel (lvbc-staff-panel).
-- This is the pass that makes them work, and fixes what that panel
-- got wrong:
--
--   * Points never move from the browser any more. Every earn and
--     spend goes through one of the member_* functions below, which
--     lock the member row, write the ledger line and the balance in
--     one transaction, and take the point value from point_rules —
--     so the Scoring page actually changes what a check-in is worth.
--   * One check-in per member per brewery day.
--   * A redemption names a rewards row, so disabling a reward or
--     changing its cost takes effect at the bar, and "once per month"
--     style limits are enforced instead of being a note.
--   * Badges award themselves. Each badge carries a rule
--     (rule_type + rule_params) that _evaluate_member_badges() checks
--     after anything that could earn one.
--
-- rewards.tier_id pointed at membership tiers (Free / Mug Club / ...),
-- but a reward's "tier" was always its level, 1–5. It becomes `level`,
-- and the "levels 3+ are for paying members" rule becomes paid_only.
--
-- New tables:
--   member_beers    the beer journal: each beer a member has tried,
--                   once. Fed by "Log beer" and by free pours. Name
--                   and style are snapshotted so a beer leaving the
--                   tap list doesn't erase the history badges count.
--   member_badges   who has earned what.
--
-- Free pours stay tied to the tap list: a beer is pourable when it is
-- active and carries the 'new_release' badge (beers.badges), one per
-- member per beer.
--
-- "Today" everywhere here is the brewery's day, America/Chicago.
--
-- RLS is unchanged in spirit: staff only. The functions are
-- security definer and check is_staff() themselves.

-- ---------- MEMBERS ----------
-- A short number staff can read off a screen and key into the POS as
-- a table number — the uuid is no use for that.
alter table members add column member_number int generated by default as identity unique;

-- ---------- QR TOKENS ----------
-- The old panel had no way to create one. Every member now gets a
-- token the moment they're added.
create or replace function create_member_qr_token()
returns trigger as $$
begin
  insert into qr_tokens (member_id, token)
  values (new.id, 'lvbc-' || replace(gen_random_uuid()::text, '-', ''));
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger members_create_qr_token
  after insert on members
  for each row execute function create_member_qr_token();

insert into qr_tokens (member_id, token)
select m.id, 'lvbc-' || replace(gen_random_uuid()::text, '-', '')
from members m
where not exists (select 1 from qr_tokens q where q.member_id = m.id);

-- ---------- CHECK-INS / LEDGER / REDEMPTIONS ----------
alter table check_ins
  add column kind text not null default 'standard' check (kind in ('standard','dd')),
  add column staff_id uuid references staff_profiles(id) on delete set null;

create index check_ins_member_idx on check_ins (member_id, checked_in_at);
create index check_ins_time_idx on check_ins (checked_in_at);

alter table points_transactions
  add column staff_id uuid references staff_profiles(id) on delete set null;

create index points_transactions_member_idx on points_transactions (member_id, created_at);

-- ---------- POINT RULES ----------
alter table point_rules add column is_active boolean not null default true;

insert into point_rules (label, transaction_type, description, points) values
  ('Designated Driver',       'checkin_dd',               'DD check-in',                      15),
  ('Event Attendance',        'event_attendance',         'Trivia, Bingo, Karaoke',           30),
  ('Special Event',           'event_special',            'Crawfish boil, release parties',   50),
  ('Bingo Round Win',         'event_win_bingo',          'Up to 3 per event',                25),
  ('Trivia Round Win',        'event_win_trivia',         'Up to 3 per event',                25),
  ('Trivia Overall Win',      'event_win_trivia_overall', 'Once per event',                   50),
  ('New Beer Tried',          'beer_journal_new',         'Per unique beer',                  10),
  ('Referral - Free Signup',  'referral_free',            'Per unique signup',                50),
  ('Referral - Paid Member',  'referral_paid',            'Per unique signup',               150),
  ('Manual Adjustment',       'manual_adjustment',        'Staff override',                    0)
on conflict (transaction_type) do nothing;

-- ---------- REWARDS ----------
alter table rewards
  drop column tier_id,
  drop column tier_limit,
  add column level int not null default 1 check (level between 1 and 5),
  add column paid_only boolean not null default false,
  -- at most limit_count redemptions per limit_period, counted per
  -- member or across the whole brewery; null = no limit
  add column limit_count int check (limit_count > 0),
  add column limit_period text check (limit_period in ('month','quarter','year')),
  add column limit_scope text not null default 'member' check (limit_scope in ('member','brewery')),
  add constraint rewards_limit_pair check ((limit_count is null) = (limit_period is null));

alter table redemptions
  add column reward_id uuid references rewards(id) on delete set null,
  add column reward_level int,
  add column staff_id uuid references staff_profiles(id) on delete set null;

create index redemptions_member_idx on redemptions (member_id, redeemed_at);

-- ---------- FREE POURS ----------
alter table free_pours
  add column staff_id uuid references staff_profiles(id) on delete set null,
  add constraint free_pours_once unique (member_id, beer_id);

-- ---------- BEER JOURNAL ----------
create table member_beers (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references members(id) on delete cascade,
  beer_id uuid references beers(id) on delete set null,
  beer_name text not null,
  beer_style text,
  tried_at timestamptz not null default now()
);

-- "unique beer" means unique by name, so a beer that is re-created on
-- the tap list later doesn't count twice
create unique index member_beers_uq on member_beers (member_id, lower(beer_name));

-- ---------- BADGES ----------
-- rule_type decides how a badge is earned; rule_params holds its
-- numbers. null rule_type = nothing awards it (catalog only).
--   first_checkin       {}
--   checkin_count       {"count": 25}
--   checkins_in_season  {"months": [3,4,5], "count": 4}   within one season
--   unique_beers        {"count": 5, "patterns": ["ipa"]} style contains any pattern; [] = any beer
--   lifetime_points     {"points": 1000}
--   anniversary         {"years": 1}
--   tier                {"tier": "Mug Club"}              held only while on that tier
--   all_of              {"badges": ["Spring Sipper", ...]}
alter table badges
  add column rule_type text check (rule_type in
    ('first_checkin','checkin_count','checkins_in_season','unique_beers','lifetime_points','anniversary','tier','all_of')),
  add column rule_params jsonb not null default '{}';

create table member_badges (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references members(id) on delete cascade,
  badge_id uuid not null references badges(id) on delete cascade,
  earned_at timestamptz not null default now(),
  unique (member_id, badge_id)
);

alter table member_beers enable row level security;
alter table member_badges enable row level security;

create policy "staff only member_beers" on member_beers for all using (is_staff()) with check (is_staff());
create policy "staff only member_badges" on member_badges for all using (is_staff()) with check (is_staff());

-- ============================================================
-- FUNCTIONS
-- ============================================================
-- Names starting with _ are internal: no caller check, so execute is
-- revoked from every API role at the bottom of this file.

create or replace function membership_today()
returns date as $$
  select (now() at time zone 'America/Chicago')::date;
$$ language sql stable;

-- Awards any badge the member now qualifies for and returns the names
-- of the ones just earned. 'tier' badges are also taken away when the
-- member leaves the tier; nothing else is ever revoked.
create or replace function _evaluate_member_badges(p_member uuid)
returns text[] as $$
declare
  m members%rowtype;
  b record;
  ok boolean;
  v_months int[];
  v_patterns text[];
  earned text[] := '{}';
begin
  select * into m from members where id = p_member;
  if not found then return earned; end if;

  -- all_of goes last so it sees badges earned earlier in this pass
  for b in
    select * from badges
    where is_active and rule_type is not null
    order by (rule_type = 'all_of'), name
  loop
    ok := false;

    if b.rule_type = 'first_checkin' then
      ok := exists (select 1 from check_ins where member_id = p_member);

    elsif b.rule_type = 'checkin_count' then
      ok := (select count(*) from check_ins where member_id = p_member)
            >= coalesce((b.rule_params->>'count')::int, 1);

    elsif b.rule_type = 'checkins_in_season' then
      v_months := array(select jsonb_array_elements_text(b.rule_params->'months')::int);
      if coalesce(array_length(v_months, 1), 0) > 0 then
        -- A season that wraps the new year (Dec–Feb) is grouped under
        -- the year it ends in.
        ok := exists (
          select 1
          from check_ins c
          cross join lateral (select c.checked_in_at at time zone 'America/Chicago' as t) x
          where c.member_id = p_member
            and extract(month from x.t)::int = any (v_months)
          group by extract(year from x.t)::int
            + case when v_months[1] > v_months[array_length(v_months, 1)]
                    and extract(month from x.t)::int >= v_months[1] then 1 else 0 end
          having count(*) >= coalesce((b.rule_params->>'count')::int, 1)
        );
      end if;

    elsif b.rule_type = 'unique_beers' then
      v_patterns := array(select jsonb_array_elements_text(coalesce(b.rule_params->'patterns', '[]'::jsonb)));
      ok := (
        select count(*) from member_beers mb
        where mb.member_id = p_member
          and (coalesce(array_length(v_patterns, 1), 0) = 0
               or exists (select 1 from unnest(v_patterns) p where mb.beer_style ilike '%' || p || '%'))
      ) >= coalesce((b.rule_params->>'count')::int, 1);

    elsif b.rule_type = 'lifetime_points' then
      ok := m.points_earned_lifetime >= coalesce((b.rule_params->>'points')::int, 0);

    elsif b.rule_type = 'anniversary' then
      ok := m.joined_at <= now() - make_interval(years => coalesce((b.rule_params->>'years')::int, 1));

    elsif b.rule_type = 'tier' then
      ok := exists (select 1 from tiers t where t.id = m.tier_id and t.name = b.rule_params->>'tier');
      if not ok then
        delete from member_badges where member_id = p_member and badge_id = b.id;
      end if;

    elsif b.rule_type = 'all_of' then
      ok := jsonb_array_length(coalesce(b.rule_params->'badges', '[]'::jsonb)) > 0
        and not exists (
          select 1 from jsonb_array_elements_text(b.rule_params->'badges') need(name)
          where not exists (
            select 1 from member_badges mb join badges b2 on b2.id = mb.badge_id
            where mb.member_id = p_member and b2.name = need.name
          )
        );
    end if;

    if ok then
      insert into member_badges (member_id, badge_id) values (p_member, b.id)
      on conflict (member_id, badge_id) do nothing;
      if found then earned := earned || b.name; end if;
    end if;
  end loop;

  return earned;
end;
$$ language plpgsql security definer set search_path = public;

-- The one place a balance changes. Caller holds the member row lock.
create or replace function _member_add_points(p_member uuid, p_type text, p_points int, p_notes text)
returns int as $$
declare
  v_balance int;
begin
  update members
  set points_balance = points_balance + p_points,
      points_earned_lifetime = points_earned_lifetime + greatest(p_points, 0)
  where id = p_member
  returning points_balance into v_balance;

  if v_balance < 0 then
    raise exception 'Not enough points';
  end if;

  insert into points_transactions (member_id, transaction_type, points, notes, processed_by, staff_id)
  values (p_member, p_type, p_points, nullif(trim(p_notes), ''),
          (select name from staff_profiles where id = auth.uid()), auth.uid());

  return v_balance;
end;
$$ language plpgsql security definer set search_path = public;

create or replace function _member_lock(p_member uuid)
returns members as $$
declare
  m members%rowtype;
begin
  if not is_staff() then raise exception 'Staff only'; end if;
  select * into m from members where id = p_member for update;
  if not found then raise exception 'Member not found'; end if;
  if not m.is_active then raise exception '% is deactivated', m.name; end if;
  return m;
end;
$$ language plpgsql security definer set search_path = public;

-- One check-in per member per brewery day. Which rule pays out:
-- DD mode, else first visit ever, else Wednesday / Thursday, else
-- standard. A second call the same day changes nothing and says so.
create or replace function member_check_in(p_member uuid, p_kind text default 'standard')
returns jsonb as $$
declare
  m members%rowtype;
  v_type text;
  v_rule point_rules%rowtype;
  v_points int;
  v_balance int;
  v_dow int;
begin
  m := _member_lock(p_member);

  if exists (
    select 1 from check_ins
    where member_id = p_member
      and (checked_in_at at time zone 'America/Chicago')::date = membership_today()
  ) then
    return jsonb_build_object('already', true, 'points', 0, 'balance', m.points_balance, 'new_badges', '[]'::jsonb);
  end if;

  v_dow := extract(dow from now() at time zone 'America/Chicago');
  v_type := case
    when p_kind = 'dd' then 'checkin_dd'
    when not exists (select 1 from check_ins where member_id = p_member) then 'checkin_first_visit'
    when v_dow = 3 then 'checkin_wednesday'
    when v_dow = 4 then 'checkin_thursday'
    else 'checkin_standard'
  end;

  select * into v_rule from point_rules where transaction_type = v_type;
  -- a rule switched off falls back to the standard check-in
  if not found or not v_rule.is_active then
    select * into v_rule from point_rules where transaction_type = 'checkin_standard';
    v_type := 'checkin_standard';
  end if;
  v_points := coalesce(v_rule.points, 0);

  insert into check_ins (member_id, kind, points_awarded, staff_id)
  values (p_member, case when p_kind = 'dd' then 'dd' else 'standard' end, v_points, auth.uid());

  v_balance := _member_add_points(p_member, v_type, v_points, null);

  return jsonb_build_object(
    'already', false, 'points', v_points, 'type', v_type, 'label', v_rule.label,
    'balance', v_balance, 'new_badges', to_jsonb(_evaluate_member_badges(p_member)));
end;
$$ language plpgsql security definer set search_path = public;

-- Points outside a check-in. 'manual_adjustment' takes any non-zero
-- amount and needs a reason; every other type pays its rule's value.
create or replace function member_award_points(p_member uuid, p_type text, p_points int default null, p_notes text default null)
returns jsonb as $$
declare
  m members%rowtype;
  v_rule point_rules%rowtype;
  v_points int;
  v_balance int;
begin
  m := _member_lock(p_member);

  if p_type like 'checkin_%' then
    raise exception 'Check-ins are recorded with a check-in, not an award';
  end if;

  if p_type = 'manual_adjustment' then
    if coalesce(p_points, 0) = 0 then raise exception 'Enter a points value'; end if;
    if nullif(trim(p_notes), '') is null then raise exception 'Enter a reason for the adjustment'; end if;
    v_points := p_points;
  else
    select * into v_rule from point_rules where transaction_type = p_type and is_active;
    if not found then raise exception 'No active scoring rule for %', p_type; end if;
    v_points := v_rule.points;
  end if;

  if m.points_balance + v_points < 0 then
    raise exception 'Balance cannot go below 0';
  end if;

  v_balance := _member_add_points(p_member, p_type, v_points, p_notes);

  return jsonb_build_object('points', v_points, 'balance', v_balance,
    'new_badges', to_jsonb(_evaluate_member_badges(p_member)));
end;
$$ language plpgsql security definer set search_path = public;

create or replace function member_redeem(p_member uuid, p_reward uuid, p_notes text default null)
returns jsonb as $$
declare
  m members%rowtype;
  r rewards%rowtype;
  v_used int;
  v_since timestamptz;
  v_balance int;
begin
  m := _member_lock(p_member);

  select * into r from rewards where id = p_reward;
  if not found or not r.is_active then raise exception 'That reward is not available'; end if;

  if r.paid_only and not exists (select 1 from tiers t where t.id = m.tier_id and t.rank > 0) then
    raise exception '% requires a paid membership', r.reward_name;
  end if;

  if m.points_balance < r.points_cost then
    raise exception 'Not enough points: % of % needed', m.points_balance, r.points_cost;
  end if;

  if not r.repeatable and exists (select 1 from redemptions where member_id = p_member and reward_id = r.id) then
    raise exception '% can only be redeemed once', r.reward_name;
  end if;

  if r.limit_count is not null then
    v_since := date_trunc(r.limit_period, now() at time zone 'America/Chicago') at time zone 'America/Chicago';
    select count(*) into v_used from redemptions
    where reward_id = r.id and redeemed_at >= v_since
      and (r.limit_scope = 'brewery' or member_id = p_member);
    if v_used >= r.limit_count then
      raise exception '% is limited to % per %', r.reward_name, r.limit_count,
        r.limit_period || case when r.limit_scope = 'brewery' then ', brewery-wide' else '' end;
    end if;
  end if;

  insert into redemptions (member_id, tier_id, reward_id, reward_level, reward_name, points_spent, processed_by, staff_id, notes)
  values (p_member, m.tier_id, r.id, r.level, r.reward_name, r.points_cost,
          (select name from staff_profiles where id = auth.uid()), auth.uid(), nullif(trim(p_notes), ''));

  v_balance := _member_add_points(p_member, 'redemption', -r.points_cost, r.reward_name);

  return jsonb_build_object('reward', r.reward_name, 'points', r.points_cost, 'balance', v_balance);
end;
$$ language plpgsql security definer set search_path = public;

-- Adds a beer to the member's journal. The first time pays the
-- 'beer_journal_new' rule; after that it's a no-op.
create or replace function member_log_beer(p_member uuid, p_beer uuid)
returns jsonb as $$
declare
  m members%rowtype;
  v_beer beers%rowtype;
  v_points int := 0;
  v_balance int;
begin
  m := _member_lock(p_member);
  v_balance := m.points_balance;

  select * into v_beer from beers where id = p_beer;
  if not found then raise exception 'Beer not found'; end if;

  insert into member_beers (member_id, beer_id, beer_name, beer_style)
  values (p_member, v_beer.id, v_beer.name, v_beer.style)
  on conflict (member_id, lower(beer_name)) do nothing;

  if not found then
    return jsonb_build_object('already', true, 'points', 0, 'balance', v_balance, 'new_badges', '[]'::jsonb);
  end if;

  select points into v_points from point_rules where transaction_type = 'beer_journal_new' and is_active;
  if coalesce(v_points, 0) <> 0 then
    v_balance := _member_add_points(p_member, 'beer_journal_new', v_points, v_beer.name);
  end if;

  return jsonb_build_object('already', false, 'points', coalesce(v_points, 0), 'balance', v_balance,
    'new_badges', to_jsonb(_evaluate_member_badges(p_member)));
end;
$$ language plpgsql security definer set search_path = public;

-- One free pour per member per new release. Checks the member in if
-- they haven't been today, and puts the beer in their journal.
create or replace function member_free_pour(p_member uuid, p_beer uuid)
returns jsonb as $$
declare
  m members%rowtype;
  v_beer beers%rowtype;
  v_checkin jsonb;
  v_journal jsonb;
begin
  m := _member_lock(p_member);

  select * into v_beer from beers where id = p_beer;
  if not found or v_beer.status <> 'active' or not ('new_release' = any (v_beer.badges)) then
    raise exception 'Free pours are only for new releases on the tap list';
  end if;

  if exists (select 1 from free_pours where member_id = p_member and beer_id = p_beer) then
    raise exception '% has already had a free pour of %', m.name, v_beer.name;
  end if;

  v_checkin := member_check_in(p_member, 'standard');

  insert into free_pours (member_id, beer_id, staff_id) values (p_member, p_beer, auth.uid());

  update check_ins set new_release_poured = true, free_pour_beer = v_beer.name
  where member_id = p_member
    and (checked_in_at at time zone 'America/Chicago')::date = membership_today();

  v_journal := member_log_beer(p_member, p_beer);

  return jsonb_build_object(
    'beer', v_beer.name, 'checkin', v_checkin, 'journal', v_journal,
    'balance', v_journal->'balance',
    'new_badges', (v_checkin->'new_badges') || (v_journal->'new_badges'));
end;
$$ language plpgsql security definer set search_path = public;

-- Tier badges follow the member's tier, whoever changes it.
create or replace function members_evaluate_badges()
returns trigger as $$
begin
  perform _evaluate_member_badges(new.id);
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger members_evaluate_badges
  after insert or update of tier_id on members
  for each row execute function members_evaluate_badges();

revoke all on function _evaluate_member_badges(uuid) from public, anon, authenticated;
revoke all on function _member_add_points(uuid, text, int, text) from public, anon, authenticated;
revoke all on function _member_lock(uuid) from public, anon, authenticated;

revoke all on function member_check_in(uuid, text) from public, anon;
revoke all on function member_award_points(uuid, text, int, text) from public, anon;
revoke all on function member_redeem(uuid, uuid, text) from public, anon;
revoke all on function member_log_beer(uuid, uuid) from public, anon;
revoke all on function member_free_pour(uuid, uuid) from public, anon;
grant execute on function member_check_in(uuid, text) to authenticated;
grant execute on function member_award_points(uuid, text, int, text) to authenticated;
grant execute on function member_redeem(uuid, uuid, text) to authenticated;
grant execute on function member_log_beer(uuid, uuid) to authenticated;
grant execute on function member_free_pour(uuid, uuid) to authenticated;

-- ============================================================
-- CATALOG — carried over from the first staff panel
-- ============================================================

insert into rewards (reward_name, level, points_cost, paid_only, repeatable, limit_count, limit_period, limit_scope) values
  ('Treasure box pick',           1,  100, false, true,  null, null,      'member'),
  ('Sticker pack',                1,  100, false, true,  null, null,      'member'),
  ('Snack item',                  1,  150, false, true,  null, null,      'member'),
  ('Koozie',                      1,  150, false, true,  null, null,      'member'),
  ('Pick trivia category',        2,  250, false, true,  1,    'month',   'member'),
  ('Pick music bingo theme',      2,  250, false, true,  1,    'month',   'member'),
  ('Wall of Regulars',            2,  300, false, true,  1,    'month',   'member'),
  ('LVBC pint glass',             2,  400, false, true,  null, null,      'member'),
  ('Free snack up to $10',        2,  400, false, true,  null, null,      'member'),
  ('LVBC t-shirt',                3,  750, true,  true,  null, null,      'member'),
  ('LVBC hat',                    3,  750, true,  true,  null, null,      'member'),
  ('LVBC hoodie',                 3, 1000, true,  true,  null, null,      'member'),
  ('Private tasting for 4',       4, 1500, true,  true,  2,    'month',   'brewery'),
  ('Custom LVBC item',            4, 2000, true,  true,  null, null,      'member'),
  ('Host private taproom event',  4, 2500, true,  true,  1,    'month',   'brewery'),
  ('Limestone wall inscription',  5, 5000, true,  false, null, null,      'member'),
  ('Brew day experience',         5, 5000, true,  false, 1,    'quarter', 'brewery');

insert into badges (name, category, rarity, border_color, description, trigger_description, rule_type, rule_params) values
  ('Hop Head',        'Explorer',   'Standard',  '#E8B84B', 'Try 5 unique IPAs',            'Try 5 unique IPAs (any sub-style)',         'unique_beers',       '{"count":5,"patterns":["ipa","india pale"]}'),
  ('Dark Side',       'Explorer',   'Standard',  '#E8B84B', 'Try 5 unique stouts',          'Try 5 unique stouts',                       'unique_beers',       '{"count":5,"patterns":["stout"]}'),
  ('Lager Loyalist',  'Explorer',   'Standard',  '#E8B84B', 'Try 5 unique lagers',          'Try 5 unique lagers or pilsners',           'unique_beers',       '{"count":5,"patterns":["lager","pils"]}'),
  ('Sour Power',      'Explorer',   'Standard',  '#E8B84B', 'Try 5 unique sours',           'Try 5 unique sour or wild ales',            'unique_beers',       '{"count":5,"patterns":["sour","wild","gose","berliner"]}'),
  ('Spring Sipper',   'Seasonal',   'Rare',      '#2AB8A6', 'Check in 4+ times Mar–May',    'Check in 4+ times during Mar–May',          'checkins_in_season', '{"months":[3,4,5],"count":4}'),
  ('Summer Regular',  'Seasonal',   'Rare',      '#2AB8A6', 'Check in 6+ times Jun–Aug',    'Check in 6+ times during Jun–Aug',          'checkins_in_season', '{"months":[6,7,8],"count":6}'),
  ('Fall Faithful',   'Seasonal',   'Rare',      '#2AB8A6', 'Check in 4+ times Sep–Nov',    'Check in 4+ times during Sep–Nov',          'checkins_in_season', '{"months":[9,10,11],"count":4}'),
  ('Winter Warmer',   'Seasonal',   'Rare',      '#2AB8A6', 'Check in 4+ times Dec–Feb',    'Check in 4+ times during Dec–Feb',          'checkins_in_season', '{"months":[12,1,2],"count":4}'),
  ('Four Seasons',    'Seasonal',   'Exclusive', '#BF5FFF', 'Earn all four seasonal badges', 'Hold all four seasonal badges',            'all_of',             '{"badges":["Spring Sipper","Summer Regular","Fall Faithful","Winter Warmer"]}'),
  ('Welcome Mat',     'Milestone',  'Standard',  '#8E92B0', 'First ever check-in',          'First ever check-in',                       'first_checkin',      '{}'),
  ('One Year Strong', 'Milestone',  'Standard',  '#8E92B0', '1-year membership anniversary', '1-year membership anniversary',            'anniversary',        '{"years":1}'),
  ('Mug Club Member', 'Membership', 'Standard',  '#2AB8A6', 'Active Mug Club membership',   'Active Mug Club membership',                'tier',               '{"tier":"Mug Club"}');
